# Generated by Django 5.1 on 2024-09-18 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "verbose_name": "Тэг мероприятия",
                "verbose_name_plural": "Тэги мероприятий",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название мероприятия")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "start_date",
                    models.DateTimeField(verbose_name="Дата и время начала"),
                ),
                (
                    "finish_date",
                    models.DateTimeField(verbose_name="Дата и время окончания"),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Изображение"
                    ),
                ),
                ("address", models.TextField(verbose_name="Адрес")),
                ("latitude", models.FloatField(verbose_name="Широта")),
                ("longitude", models.FloatField(verbose_name="Долгота")),
                ("eco_balance", models.IntegerField(verbose_name="Эко-баллы")),
                ("vk_chat_id", models.IntegerField(blank=True, null=True)),
                ("vk_chat_link", models.URLField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(to="events.eventtag", verbose_name="Тэги"),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["-start_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="AssistanceOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistance_offers",
                        to="organizations.organization",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistance_offers",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение помощи",
                "verbose_name_plural": "Предложения помощи",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Билет",
                "verbose_name_plural": "Билеты",
            },
        ),
    ]
