# Generated by Django 5.1 on 2024-09-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                ("name", models.TextField()),
            ],
            options={"verbose_name": "Тэг новости", "verbose_name_plural": "Тэги новостей",},
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                ("name", models.TextField(verbose_name="Название новости")),
                ("description", models.TextField(verbose_name="Описание новости")),
                ("full_text", models.TextField(verbose_name="Полный текст")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.FileField(blank=True, null=True, upload_to="", verbose_name="Изображение"),),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
                ("tags", models.ManyToManyField(to="news.newstag", verbose_name="Тэги"),),
            ],
            options={"verbose_name": "Новость", "verbose_name_plural": "Новости",},
        ),
    ]
