# Generated by Django 5.1 on 2024-09-18 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.TextField(verbose_name="Полное название")),
                ("short_name", models.TextField(verbose_name="Короткое название")),
                ("address", models.TextField(verbose_name="Адрес")),
                ("ogrn", models.TextField(verbose_name="ОРГН")),
                ("inn", models.TextField(verbose_name="ИНН")),
                ("kpp", models.TextField(verbose_name="КПП")),
                ("okpo", models.TextField(verbose_name="ОКПО")),
                ("director_full_name", models.TextField(verbose_name="Директор")),
                ("director_inn", models.TextField(verbose_name="Директор ИНН")),
                ("activities", models.TextField(verbose_name="Виды деятельности")),
                ("reg_date", models.DateField(verbose_name="Дата регистрации")),
                ("phone", models.TextField(verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Изображение"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="organizations", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
    ]
